# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:1531
msgid "Live migration timed out. Aborting migration"
msgstr "Dépassement du délai d'attente de la migration active. Abandon de la migration"

#: nova_powervm/virt/powervm/live_migration.py:376
msgid "Live migration failed."
msgstr "Echec de la migration active."

#: nova_powervm/virt/powervm/live_migration.py:439
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "Echec de récupération de la migration avec l'erreur %s"

#: nova_powervm/virt/powervm/live_migration.py:467
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"Echec de l'abandon de la migration active. Erreur non bloquante. Exception "
"consignée ci-dessous."

#: nova_powervm/virt/powervm/vif.py:119
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "Echec commande push d'événement VIF personnalisé.  %s"

#: nova_powervm/virt/powervm/vif.py:370
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "Impossible de débrancher le VIF avec l'adresse mac %(mac)s pour l'instance %(inst)s."

#: nova_powervm/virt/powervm/vm.py:647
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "Echec de suppression de la machine virtuelle : LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:263
#, python-format
msgid "Disk %s not found during resize."
msgstr "Disque %s introuvable lors du redimensionnement."

#: nova_powervm/virt/powervm/disk/ssp.py:333
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "Erreur lors de la vérification du stockage partagé, exception=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "Impossible de mettre à jour la mémoire rémanente (NVRAM) : %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"Impossible de retirer les VIF de l'instance %(inst)s car le système n'est "
"pas dans un état correct.  Motif consigné par le système : %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"Impossible de créer de VIF pour l'instance %(sys)s.  La machine virtuelle "
"n'acceptait pas le branchement de VIF.  Motif du système : %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Erreur lors de l'attente de création de VIF pour l'instance %(sys)s"

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "Echec connexion VIF pour rappel sur l'événement %(event)s pour l'instance %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Impossible de stocker la mémoire rémanente (NVRAM) pour l'instance %(name)s. Exception : %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Impossible de supprimer la mémoire rémanente pour l'instance %(name)s. Exception : %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:214
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "Impossible de déconnecter les volumes de la machine virtuelle : %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:216
#: nova_powervm/virt/powervm/volume/vscsi.py:340
#, python-format
msgid "Error: %s"
msgstr "Erreur : %s"

#: nova_powervm/virt/powervm/volume/npiv.py:517
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"Les mappages n'ont pas pu trouver de VIOS approprié. Les mappages de port étaient %s."

#: nova_powervm/virt/powervm/volume/vscsi.py:338
msgid "Cannot detach volumes from virtual machine"
msgstr "Impossible de déconnecter des volumes de la machine virtuelle"

# ENGL1SH_VERS10N 32661_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV133AAP001 2
