# Translations template for nova_powervm.
# Copyright 2015, 2017 IBM Corp.
# This file is distributed under the same license as the nova_powervm
# project.
# Automatically generated, 2017.
#
msgid ""
msgstr ""
"Project-Id-Version: nova_powervm 4.0.1.dev5\n"
"Report-Msgid-Bugs-To: EMAIL@ADDRESS\n"
"POT-Creation-Date: 2017-04-20 10:07-0400\n"
"PO-Revision-Date: 2017-04-20 10:07-0400\n"
"Last-Translator: Automatically generated\n"
"Language-Team: none\n"
"MIME-Version: 1.0\n"
"Content-Type: text/plain; charset=UTF-8\n"
"Content-Transfer-Encoding: 8bit\n"
"Generated-By: Babel 2.4.0\n"

#: nova_powervm/virt/powervm/driver.py:1531
msgid "Live migration timed out. Aborting migration"
msgstr "La migrazione live è scaduta. Interruzione della migrazione"

#: nova_powervm/virt/powervm/live_migration.py:376
msgid "Live migration failed."
msgstr "Migrazione live non riuscita."

#: nova_powervm/virt/powervm/live_migration.py:439
#, python-format
msgid "Migration recover failed with error: %s"
msgstr "Ripristino migrazione non riuscito con errore: %s"

#: nova_powervm/virt/powervm/live_migration.py:467
msgid ""
"Abort of live migration has failed. This is non-blocking. Exception is "
"logged below."
msgstr ""
"Interruzione migrazione live non riuscita. Il problema non è bloccante. L'eccezione è "
"registrata di seguito."

#: nova_powervm/virt/powervm/vif.py:119
#, python-format
msgid "Custom VIF event push failed.  %s"
msgstr "Push di evento VIF personalizzato non riuscito.  %s"

#: nova_powervm/virt/powervm/vif.py:370
#, python-format
msgid "Unable to unplug VIF with mac %(mac)s for instance %(inst)s."
msgstr "Impossibile scollegare il VIF con mac %(mac)s per l'istanza %(inst)s."

#: nova_powervm/virt/powervm/vm.py:647
#, python-format
msgid "Virtual machine delete failed: LPARID=%s"
msgstr "Eliminazione della macchina virtuale non riuscita: LPARID=%s"

#: nova_powervm/virt/powervm/disk/localdisk.py:263
#, python-format
msgid "Disk %s not found during resize."
msgstr "Disco %s non trovato durante il ridimensionamento."

#: nova_powervm/virt/powervm/disk/ssp.py:333
#, python-format
msgid "Error checking for shared storage. exception=%s"
msgstr "Errore durante il controllo della memoria condivisa, eccezione=%s"

#: nova_powervm/virt/powervm/nvram/manager.py:109
#: nova_powervm/virt/powervm/nvram/manager.py:178
#, python-format
msgid "Could not update NVRAM: %s"
msgstr "Impossibile aggiornare NVRAM: %s"

#: nova_powervm/virt/powervm/tasks/network.py:66
#, python-format
msgid ""
"Unable to remove VIFs from instance %(inst)s because the system is not in a "
"correct state.  The reason reported by the system is: %(reason)s"
msgstr ""
"Impossibile rimuovere i VIF dall'istanza %(inst)s poiché il sistema non è in "
"uno stato corretto.  Il motivo riportato dal sistema è: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:154
#, python-format
msgid ""
"Unable to create VIF(s) for instance %(sys)s.  The VM was in a state where "
"VIF plugging is not acceptable.  The reason from the system is: %(reason)s"
msgstr ""
"Impossibile creare i VIF per l'istanza %(sys)s.  La VM era in uno stato in cui "
"il collegamento di VIP non è accettabile.  Il motivo dal sistema è: %(reason)s"

#: nova_powervm/virt/powervm/tasks/network.py:207
#, python-format
msgid "Error waiting for VIF to be created for instance %(sys)s"
msgstr "Errore durante l'attesa della creazione del VIF per l'istanza %(sys)s"

#: nova_powervm/virt/powervm/tasks/network.py:221
#, python-format
msgid "VIF Plug failure for callback on event %(event)s for instance %(uuid)s"
msgstr "Errore di collegamento VIF per la callback sull'evento %(event)s per l'istanza %(uuid)s"

#: nova_powervm/virt/powervm/tasks/vm.py:283
#, python-format
msgid "Unable to store NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Impossibile memorizzare NVRAM per l'istanza %(name)s. Eccezione: %(reason)s"

#: nova_powervm/virt/powervm/tasks/vm.py:313
#, python-format
msgid "Unable to delete NVRAM for instance %(name)s. Exception: %(reason)s"
msgstr "Impossibile eliminare NVRAM per l'istanza %(name)s. Eccezione: %(reason)s"

#: nova_powervm/virt/powervm/volume/iscsi.py:214
#, python-format
msgid "Cannot detach volumes from virtual machine: %s"
msgstr "Impossibile scollegare i volumi dalla macchina virtuale: %s"

#: nova_powervm/virt/powervm/volume/iscsi.py:216
#: nova_powervm/virt/powervm/volume/vscsi.py:340
#, python-format
msgid "Error: %s"
msgstr "Errore: %s"

#: nova_powervm/virt/powervm/volume/npiv.py:517
#, python-format
msgid ""
"Mappings were not able to find a proper VIOS. The port mappings were %s."
msgstr ""
"Le associazioni non sono state in grado di trovare un VIOS appropriato. Le associazioni porta erano %s."

#: nova_powervm/virt/powervm/volume/vscsi.py:338
msgid "Cannot detach volumes from virtual machine"
msgstr "Impossibile scollegare i volumi dalla macchina virtuale"

# ENGL1SH_VERS10N 32661_5 DO NOT REMOVE OR CHANGE THIS LINE
# T9N_SRC_ID 44
# T9N_SH1P_STR1NG PV133AAP001 2
